services:
  # FASTAPI BACKEND
  api:
    build: .
    container_name: opus_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:pass@db:5432/opus
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: admin
      S3_SECRET_KEY: admin123
      S3_BUCKET: opus
      REDIS_BROKER: redis://redis:6379/0
      RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
    command: uvicorn opus_starter_bot:app --host 0.0.0.0 --port 8000

  # CELERY WORKER
  worker:
    build: .
    container_name: opus_worker
    environment:
      DATABASE_URL: postgresql://postgres:pass@db:5432/opus
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: admin
      S3_SECRET_KEY: admin123
      S3_BUCKET: opus
      REDIS_BROKER: redis://redis:6379/0
      RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      api:
        condition: service_started
      db:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
    command: celery -A opus_starter_bot.celery_app worker --loglevel=info

  # REDIS (Celery broker)
  redis:
    image: redis:7
    container_name: opus_redis
    ports:
      - "6379:6379"

  # POSTGRES
  db:
    image: postgres:15
    container_name: opus_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: opus
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 5s

  # MINIO (S3 STORAGE)
  minio:
    image: quay.io/minio/minio
    container_name: opus_minio
    command: server /data --console-address :9001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # MinIO console
    volumes:
      - minio_data:/data

  # DJANGO UI
  studio:
    build: .
    container_name: opus_studio
    command: python dashboard/manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    environment:
      POSTGRES_DB: opus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

      # local and docker internal urls
      MINIO_PUBLIC_BASE: http://localhost:9000
      MINIO_INTERNAL_BASE: http://minio:9000
      API_PUBLIC_BASE: http://localhost:8000    ## Django talks to Client 
      API_INTERNAL_BASE: http://api:8000        ## Django talks to FastAPI via internal Docker DNS

      S3_BUCKET: opus
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started
      minio:
        condition: service_started

# VOLUMES
volumes:
  pgdata:
  minio_data:
